import * as Schema from "effect/Schema";

import {
  EnvironmentId,
  IsoDateTime,
  NonNegativeInt,
  ThreadId,
  TrimmedNonEmptyString,
} from "./baseSchemas.ts";

/**
 * Server-side dictation: a client uploads a recording through the signed
 * attachment upload route, then starts a job that the server transcribes with
 * the environment's OpenAI key. Every job's state reaches every subscribed
 * client, so the marker a client drops into a draft can be filled wherever the
 * draft lives.
 */

/** Generated by the client, so it can place its marker before the job exists. */
export const DictationJobId = TrimmedNonEmptyString.pipe(Schema.brand("DictationJobId"));
export type DictationJobId = typeof DictationJobId.Type;

/** The names the Symmetria Shell protocol already uses. */
export const DictationMode = Schema.Literals(["clipboard", "inject", "submit"]);
export type DictationMode = typeof DictationMode.Type;

export const DictationThreadTarget = Schema.Struct({
  kind: Schema.Literal("thread"),
  environmentId: EnvironmentId,
  threadId: ThreadId,
});
export type DictationThreadTarget = typeof DictationThreadTarget.Type;

/** A client-local draft that has no thread yet. */
export const DictationDraftTarget = Schema.Struct({
  kind: Schema.Literal("draft"),
  draftId: TrimmedNonEmptyString,
});
export type DictationDraftTarget = typeof DictationDraftTarget.Type;

/** `null` when the recording is only saved, with no draft to fill. */
export const DictationTarget = Schema.NullOr(
  Schema.Union([DictationThreadTarget, DictationDraftTarget]),
);
export type DictationTarget = typeof DictationTarget.Type;

export const DictationJobStatus = Schema.Literals(["transcribing", "completed", "failed"]);
export type DictationJobStatus = typeof DictationJobStatus.Type;

export const DictationJob = Schema.Struct({
  id: DictationJobId,
  target: DictationTarget,
  mode: DictationMode,
  status: DictationJobStatus,
  text: Schema.optional(Schema.String),
  /** A readable reason, present when `status` is `failed`. */
  failure: Schema.optional(Schema.String),
  durationMs: NonNegativeInt,
  createdAt: IsoDateTime,
  completedAt: Schema.optional(IsoDateTime),
});
export type DictationJob = typeof DictationJob.Type;

export const DictationStartInput = Schema.Struct({
  jobId: DictationJobId,
  /** An attachment uploaded with the `type: "file"` upload variant. */
  attachmentId: TrimmedNonEmptyString,
  durationMs: NonNegativeInt,
  mode: DictationMode,
  target: DictationTarget,
});
export type DictationStartInput = typeof DictationStartInput.Type;

export const DictationJobActionInput = Schema.Struct({
  jobId: DictationJobId,
});
export type DictationJobActionInput = typeof DictationJobActionInput.Type;

export const DictationSetModeInput = Schema.Struct({
  jobId: DictationJobId,
  mode: DictationMode,
});
export type DictationSetModeInput = typeof DictationSetModeInput.Type;

export const DictationSubscribeInput = Schema.Struct({});
export type DictationSubscribeInput = typeof DictationSubscribeInput.Type;

/**
 * A subscription sends a `snapshot` of every kept job, then one `upsert` per
 * change. The server sends a new `snapshot` when jobs expire or are evicted;
 * it replaces the client's whole list. A client slower than the changes may
 * receive only the latest state of a job.
 */
export const DictationJobEvent = Schema.Union([
  Schema.Struct({
    type: Schema.Literal("snapshot"),
    jobs: Schema.Array(DictationJob),
  }),
  Schema.Struct({
    type: Schema.Literal("upsert"),
    job: DictationJob,
  }),
]);
export type DictationJobEvent = typeof DictationJobEvent.Type;

export class DictationError extends Schema.TaggedError<DictationError>()("DictationError", {
  detail: Schema.String,
}) {}
